### ISSUE TITLE
Make the multiplayer at least use touch inputs rather than clicks

### ISSUE THREAD

**Issue by Grub0** [atmEthanBehar/TappinZ#9]
If you try and click more than one place on the screen at once, it does not work. So we may have to get an array of the touches and do a collision detect rather than using the click functions of the unity UI objects.

**Comment by atmEthanBehar** [comment]
Maybe we need a second touch registration or canvas for the split multiplayer - i highly doubt unity limited their ui system to 1 touch.

**Comment by Grub0** [comment]
When you think about it though, these might be using the same system as "OnClick" which is designed for mice, so it would make sense to only be able to accept one click at a time, since with a mouse the pointer can only be clicking in one place at any given time.

**Comment by atmEthanBehar** [comment]
we'll have to more research to double check this. I don't want to make a big change if the only thing we have to do is add like a Touch Register instead of a Mouse Register.

**Comment by Grub0** [comment]
I tested this on a device, and it worked fine without changing anything. So I can close this issue.
